version: '3.9'

services:

  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/tododb
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdaten:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tododb
  
  tool:
    image: phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on: 
      - db

volumes:
  dbdaten: